### ISSUE TITLE
What are the intended behaviour of decycle's and cycle's parameters?

### ISSUE THREAD

**Issue by lezsakdomi** [YChebotaev/json-decycle#4] opened 2018-05-22 19:05 UTC
It looks like the code is prepared for a simpler use:
```
const decycle = require('json-decycle').decycle;
console.log('decycled', decycle(someCircularObject));
```
but there is just a dual return.

**Comment by lezsakdomi** [comment] 2018-05-22 19:06
My current workaround:
```
console.log(JSON.parse(JSON.stringify(object, decycle())))
```

**Comment by bminer** [comment] 2018-05-23 14:20
Could be duplicate of #1 but not sure.  Can you provide more details about this?

**Comment by lezsakdomi** [comment] 2018-05-24 20:25
Phew. I can't be more clear.

The code in the issue should do what the code in my first comment does.

Maybe I'll patch it when I would have time.

**Comment by YChebotaev** [comment] 2022-03-11 15:09
@lezsakdomi `decycle()` and `retrocycle()` returns [`replacer`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) and [`parser`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse) thats intend to pass as 2nd arg of `JSON.stringify`/`parse` respectively:

```javascript
JSON.stringify(object, decycle())
```

↑ this is correct usage of the library.

I've made them as a factory functions for api stability. I guess in the future there may be need in some kind of configuration.

For now `decycle()`/`retrocycle()` takes no options and it looks wired but if needed, options may be added without api breaking-change.

**Closed as completed by YChebotaev** 2022-03-11 15:09 UTC
